// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );





"use client";

import { useState } from "react";
import Navbar from "../components/Navbar";
import LoginModal from "../components/LoginModal";
import Footer from "../components/Footer"; // ✅ IMPORT FOOTER
import "./globals.css";

export default function RootLayout({ children }) {
  const [isLoginOpen, setIsLoginOpen] = useState(false);

  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">

        {/* Navbar */}
        <Navbar onLoginClick={() => setIsLoginOpen(true)} />

        {/* Page Content */}
        <main className="flex-grow">
          {children}
        </main>

        {/* Footer (GLOBAL) */}
        <Footer />

        {/* Login Modal */}
        {isLoginOpen && (
          <LoginModal onClose={() => setIsLoginOpen(false)} />
        )}

      </body>
    </html>
  );
}
